#!/bin/bash
mylog=~/app-root/data/my.log

echo "---------------------" >> mylog
date >> mylog
echo "---------------------" >> mylog
ls ~/app-root/repo/ -al >> mylog
echo ${OPENSHIFT_LOG_DIR}mylog >> mylog
